# Numpy - Exercices

Voici une série de tests pour vérifier ses connaissances en Numpy. Le but est que cette bibliothèque et la programmation vectorielle qu'elle implique deviennent naturelles. Il faut oublier la programmation classique avec des boucles (il ne faut pas utiliser de boucle `for` ou autre dans cette feuille en dehors de construction de liste en compréhension).

Les fonctions ne doivent jamais modifier leurs arguments.

Les exercices indiquent le nombre de lignes attendu de la réponse. Cela comprend l'en-tête de la fonction lorsqu'il y en a une.

Chaque exercise compte pour 2 points sur 20.

Pensez à tester vos résultats.

In [5]:
import numpy as np

A1 = np.arange(12).reshape(3,4)
A2 = np.random.randint(-10, 10, size=(5,5))
print(A1, '\n')
print(A2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ -2   7   1  -9  -2]
 [ -7  -3  -7   0   0]
 [  5  -6  -2   1   4]
 [ -6 -10  -3   7  -3]
 [-10  -6  -4   2   6]]


### Matrice carrée

Créer la matrice carrée 5x5 qui contient les 25 premiers entiers, de 1 à 25.

1 ligne

In [3]:
np.arange(1,26).reshape([5,5])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Norme d'un vecteur

Retourner la norme euclidienne d'un vecteur sans utiliser la fonction `norm`.

2 lignes

In [14]:
def mynorm(v):
    return np.sqrt(v @ v)
print(mynorm(np.array([3,4])))
print(mynorm(np.array([1,2,3,4,3,5])))

5.0
8.0


### Sous-matrice

Extraire la sous-matrice de taille (n-2)x(m-2) qui retire les bords de la matrice A de taille nxm.

2 lignes

In [15]:
def mysubmat(A):
    return A[1:-1, 1:-1]
print(mysubmat(A1))

[[5 6]]


### Trace

Retourner la trace d'une matrice sans utiliser la fonction `trace` (à vous de chercher les éléments qui vous manquent).

2 lignes

In [24]:
def mytrace(A):
    return A.diagonal().sum()
print(mytrace(A1 @ A1.T))

506


### Matrice de multiples de 3

Arrondir la matrice donnée au multiple de 3 le plus proche (pour chaque valeur).

2 lignes

In [26]:
def round3(A):
    return 3 * (A / 3).round()
print(round3(A1))

[[ 0.  0.  3.  3.]
 [ 3.  6.  6.  6.]
 [ 9.  9.  9. 12.]]


### Nombre de 9

Compter le nombre de 9 dans une matrice d'entiers A donnée en paramètre.

2 lignes

In [31]:
def nb9(A):
    return (A==9).sum()
print(nb9(A1))

1


### Colonne qui a la plus petite moyenne

Retourner l'indice de la colonne d'une matrice ayant la plus petite moyenne.

2 lignes

In [32]:
def min_col_mean(A):
    return A.mean(axis=0).argmin()
print(min_col_mean(A1))

0


### ChessSum

On regarde la matrice comme un échequier avec des cases blanches et des cases noires qui alternent. La case en [0,0] est noire. 
Calculer la somme des valeurs sur les cases blanches.

2 lignes

In [33]:
def chess_sum(A):
    return A[1::2,::2].sum() + A[::2, 1::2].sum()
print(chess_sum(A1))

34


### Valeurs uniques

Donner la liste des valeurs uniques (qui n'apparaissent qu'une fois) dans un tableau numpy (la fonction `unique` sera utile).

3 lignes

In [1]:
def unique_vals(A):
    val, nb = np.unique(A, return_counts=True)
    return val[nb == 1]
print(unique_vals(A1 @ A1.T))

NameError: name 'A1' is not defined

### Plans d'un tenseur

Extraire tous les plans d'un tenseur 3d (c.à d. une matrice 3d). On retourne une liste de tableaux.

5 lignes (2 lignes avec la fonction `take`)

In [41]:
def extract_planes(T):
    res1 = [T[i,:,:] for i in range(T.shape[0])]
    res2 = [T[:,j,:] for j in range(T.shape[1])]
    res3 = [T[:,:,k] for k in range(T.shape[2])]
    return res1 + res2 + res3

def extract_planes2(T):
    return [T.take(i, axis=d) for d in range(3) for i in range(T.shape[d])]
A3 = np.arange(12).reshape(3,2,2)
print(extract_planes(A3))

[array([[0, 1],
       [2, 3]]), array([[4, 5],
       [6, 7]]), array([[ 8,  9],
       [10, 11]]), array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]]), array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]]), array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])]
