In [30]:
import numpy as np
import numpy.linalg as lin
np.set_printoptions(precision=4, linewidth=150, suppress=True)

## 1. Transformations isométriques

Écrire la matrice 2x2 de rotation sur 45 dégrés, au sens trigonométrique (contre la montre), autour de l'origine du plan en 2D.  (Attention à la conversion dégrés / radians.)

In [31]:
R = # votre code ici

# pour tester
print(R @ [1,0])
print(R @ [0,1])

[0.7071 0.7071]
[-0.7071  0.7071]


Définir la matrice de rotation inverse à `R`, sur -45 dégrés.

In [32]:
Rinv = # votre code ici

# pour tester
print(Rinv @ [1,0])
print(Rinv @ R @ [1,0])

[ 0.7071 -0.7071]
[1. 0.]


Écrire une transformation qui prend un point `v=[x,y]` comme entrée,
applique la rotation sur 45 dégrées,
puis une translation le long le vecteur `[2,0]`,
puis la rotation sur -45 dégrées.

In [33]:
def mytra(v):
    # votre code ici

# pour tester
print(mytra(np.array([1,0])))
print(mytra(np.array([0,1])))

[ 2.4142 -1.4142]
[ 1.4142 -0.4142]


Votre transformation est-elle un automorphisme linéaire ? Justifier.

## 2. Valeurs et vecteurs propres

Soit la matrice $A=\begin{pmatrix}0&1\\1&1\end{pmatrix}$.
Nous calculons ses valeurs et vecteurs propres.

In [104]:
A = np.array([[0,1], [1,1]])
print(A)
print(lin.eig(A))

[[0 1]
 [1 1]]
EigResult(eigenvalues=array([-0.618,  1.618]), eigenvectors=array([[-0.8507, -0.5257],
       [ 0.5257, -0.8507]]))


Calculer les valeurs et vecteurs propres de la matrice $A^2$ (sans se soucier de l'efficacité du programme).

In [105]:
# votre code ici

EigResult(eigenvalues=array([0.382, 2.618]), eigenvectors=array([[-0.8507, -0.5257],
       [ 0.5257, -0.8507]]))


Écrire une fonction qui, pour une entrée $n$, calcule les valeurs et vecteurs propres de $A^n$.

In [106]:
def vvp(n):
    # votre code ici

# pour tester
print(vvp(1))
print(vvp(0))
print(vvp(5))

EigResult(eigenvalues=array([-0.618,  1.618]), eigenvectors=array([[-0.8507, -0.5257],
       [ 0.5257, -0.8507]]))
EigResult(eigenvalues=array([1., 1.]), eigenvectors=array([[1., 0.],
       [0., 1.]]))
EigResult(eigenvalues=array([-0.0902, 11.0902]), eigenvectors=array([[-0.8507, -0.5257],
       [ 0.5257, -0.8507]]))


Diagonaliser la matrice $A$.

In [107]:
valp, vecp = vvp(1)
D = # votre code ici
P = # votre code ici

# pour tester
print(P @ D @ lin.inv(P))

[[-0.  1.]
 [ 1.  1.]]


Utiliser la diagonalisation de $A$ pour calculer les valeurs et vecteurs propres de $A^{20}$ de manière efficace.

In [114]:
# votre code ici

EigResult(eigenvalues=array([    0.0001, 15126.9999]), eigenvectors=array([[-0.8507, -0.5257],
       [ 0.5257, -0.8507]]))

## 3. La suite de Perrin

La suite de Perrin est définie par $x_0 = 3$, $x_1 = 0$, $x_2 = 2$ et
$$x_{n+3} = x_{n+1} + x_n$$
pour $n\ge 0$.
Les dix premiers termes sont donc
$3, 0, 2, 3, 2, 5, 5, 7, 9, 12$.

Notons bien l'analogie avec la séquence de Fibonacci, sauf pour le fait qu'ici on saute un terme à chaque sommation récursive.

Définir une matrice $T$ tel que
$\begin{bmatrix}
x_{n+1} \\
x_{n+2} \\
x_{n+3}
\end{bmatrix}
=
T
\begin{bmatrix}
x_n \\
x_{n+1} \\
x_{n+2}
\end{bmatrix}$.

In [83]:
T = # votre code ici

# pour tester
print(T @ np.array([3,0,2]))
print(T @ T @ np.array([3,0,2]))
print(T @ T @ T @ np.array([3,0,2]))

[0 2 3]
[2 3 2]
[3 2 5]


Écrire une fonction qui, en utilisant la matrice $T$ et la formule du terme général d'une suite géométrique, calcule la $n$-ème valeur de la suite de Perrin.

In [85]:
def perrin(n):
    # votre code ici

# pour tester
print(perrin(4))
print(perrin(9))

2
12


Diagonaliser la matrice $T$.

In [86]:
valp, vecp = lin.eig(T) # c'est des complexes, c'est normal
D = # votre code ici
P = # votre code ici

# pour tester
print(P @ D @ lin.inv(P))

[[-0.-0.j  1.-0.j  0.-0.j]
 [ 0.-0.j  0.-0.j  1.+0.j]
 [ 1.-0.j  1.-0.j  0.+0.j]]


Utiliser la diagonalisation pour calculer de manière efficace la $n$-ième valeur de la suite de Perrin et vérifier que, pour $2\le n\le 50$, $x_n$ est divisible par $n$ si, et seulement si, $n$ est un nombre premier.

In [100]:
# votre code ici

2 2
3 3
5 5
7 7
11 22
13 39
17 119
19 209
23 644
29 3480
31 6107
37 33004
41 101639
43 178364
47 549289


/tmp/ipykernel_325073/855355815.py:4: ComplexWarning: Casting complex values to real discards the imaginary part
  x = v[0].astype('float')


### Postscriptum

La suite de Perrin satisfait la propriété que *si $n$ est un nombre premier, alors $x_n$ est divisible par $n$*.
La réciproque de cela n'est **pas vrai**, mais le plus petit contre-exemple se trouve à $n=271\,441$ (!), et en général il y a peu de nombres non-premiers de ce type.
(Ils s'appellent *nombres pseudo-premiers de Perrin*.)
Cette propriété est à la base d'un **test de primalité** probabiliste, similaire au test de Fermat.