In [2]:
import numpy as np
import numpy.linalg as lin

$A$ : notre matrice de liens

On calcule $v := v A$ quelques fois

In [16]:
A=np.array([[0,1,1,1], [0,0,1,1], [1,0,0,0], [1,0,1,0]])
print(A)
v=np.array([1,1,1,1])
print(v)
v=v@A
print(v)
v=v@A
print(v)

[[0 1 1 1]
 [0 0 1 1]
 [1 0 0 0]
 [1 0 1 0]]
[1 1 1 1]
[2 1 3 2]
[5 2 5 3]


Maintenant, l'itération $v := v A$ ; $v := v * 4 / ||v||_1$

In [7]:
def iterate(n):
    v=np.array([1,1,1,1])
    print(v)
    for i in range(n):
        #v=v@A*4/linalg.norm(v,1)
        v=v@A; v=v*4/lin.norm(v,1)
        print(v)
iterate(20)

[1 1 1 1]
[1.  0.5 1.5 1. ]
[1.33333333 0.53333333 1.33333333 0.8       ]
[1.06666667 0.66666667 1.33333333 0.93333333]
[1.17241379 0.55172414 1.37931034 0.89655172]
[1.16814159 0.60176991 1.34513274 0.88495575]
[1.14027149 0.59728507 1.35746606 0.90497738]
[1.1627907  0.58604651 1.35813953 0.89302326]
[1.15375447 0.59594756 1.35399285 0.89630513]
[1.15403423 0.59168704 1.35696822 0.89731051]
[1.15647538 0.59203512 1.35591094 0.89557855]
[1.15452645 0.59302139 1.35584499 0.89660717]
[1.15529897 0.59216495 1.35620619 0.8963299 ]
[1.15528108 0.59252993 1.35594941 0.89623958]
[1.15506768 0.5925026  1.35603957 0.89639014]
[1.1552361  0.59241622 1.35604611 0.89630157]
[1.15517005 0.5924903  1.35601461 0.89632504]
[1.15517105 0.59245905 1.35603677 0.89633313]
[1.1551897  0.59246117 1.35602908 0.89632005]
[1.15517515 0.59246873 1.35602845 0.89632767]
[1.15518079 0.59246233 1.35603119 0.89632569]


Cela converge assez rapidemment

Maintenant, convertir $A$ en matrice stochastique (et la transposer)

In [26]:
A=np.array([[0,1,1,1], [0,0,1,1], [1,0,0,0], [1,0,1,0]])
A=A.astype(float)
for i in range(len(A)):
    total = sum(A[i])
    A[i]=[float(x)/total for x in A[i]]
A=A.T
print(A)

[[0.         0.         1.         0.5       ]
 [0.33333333 0.         0.         0.        ]
 [0.33333333 0.5        0.         0.5       ]
 [0.33333333 0.5        0.         0.        ]]


Introduire le facteur d'amortissement

In [39]:
B=np.ones(A.shape)
p=0.15
M = (1-p)*A + p/len(A)*B
print(M)

[[0.0375     0.0375     0.8875     0.4625    ]
 [0.32083333 0.0375     0.0375     0.0375    ]
 [0.32083333 0.4625     0.0375     0.4625    ]
 [0.32083333 0.4625     0.0375     0.0375    ]]


Maintenant, l'itération

In [51]:
v=0.25*np.ones(4)
for i in range(10):
    v = M@v
    print(v)

[0.35625    0.10833333 0.32083333 0.21458333]
[0.40140625 0.1384375  0.27567708 0.18447917]
[0.35022917 0.15123177 0.28847135 0.21006771]
[0.37197943 0.1367316  0.29028388 0.2010051 ]
[0.36966846 0.14289417 0.28643227 0.2010051 ]
[0.36639459 0.1422394  0.28839659 0.20296942]
[0.3688991  0.1413118  0.28802555 0.20176355]
[0.36807122 0.14202141 0.28782844 0.20207893]
[0.36803771 0.14178685 0.28802949 0.20214595]
[0.3682371  0.14177735 0.28794879 0.20203676]


Cela donne le plus d'importance à la page 1 (!)

Réessayons avec un facteur d'amortissement plus petit

In [52]:
p=0.05
M = (1-p)*A + p/len(A)*B
v=0.25*np.ones(4)
for i in range(10):
    v = M@v
    print(v)

[0.36875    0.09166667 0.32916667 0.21041667]
[0.42515625 0.12927083 0.27276042 0.1728125 ]
[0.35370833 0.14713281 0.2906224  0.20853646]
[0.38764609 0.12450764 0.29345054 0.19439572]
[0.38361598 0.1352546  0.28673369 0.19439572]
[0.37723498 0.1339784  0.2905623  0.19822433]
[0.38269074 0.13195774 0.28975404 0.19559748]
[0.38067514 0.1336854  0.28927413 0.19636533]
[0.38058396 0.13304713 0.28982122 0.19654769]
[0.38119032 0.13301825 0.28957579 0.19621564]


Le résultat est encore plus convaincant : la page 1 est la plus importante