In [1]:
import numpy as np

np.set_printoptions(precision=10, linewidth=150, suppress=True)

## Améliorer Jacobi

Lorsqu'on écrit une itération de la méthode de Jacobi avec l'ensemble des coefficients, on constate que
si on calcule la nouvelle valeur de **x** élément par élement alors lorsqu'on veut mettre à jour `x[1]`, on connait déjà `x[0]`. Idem lorsqu'on met à jour `x[2]` on connait déjà `x[0]` et `x[1]`, etc.

L'idée de la version améliorée de Jacobi est d'utiliser la nouvelle valeur de `x[0]` et non pas l'ancienne comme c'est le cas dans le Jacobi standard. Ainsi en utilisant des valeurs mises à jour on peut espérer converger plus vite.

Dans ce cas chaque itération demande un calcul ligne par ligne et donc une boucle `for` dans la boucle `for` sur les itérations.

#### Test d'arrêt

On ajoutera un argument `error` à la fonction qui indique la précision désirée du résultat. Par
défaut sa valeur est de `1E-6` et pour offrir une bonne garantie on arrête l'algorithme lorsque
$||x_{t+1} - x_t|| < \texttt{error}\, / \, 10$.

In [3]:
def solve_jacobi2(A, b, error=1E-6, verbose=False):
    # version avec double boucle (for dans le while des itérations)
    M = np.diag(A)        # attention, c'est un vecteur
    N = np.diag(M) - A    # np.diag d'une matrice donne un vecteur, 
                          # np.diag d'un vecteur donne une matrice
    x = np.random.random(len(b))
    previous_x = np.zeros(len(b))
    err = (error / 10) ** 2
    while np.sum(np.square(x - previous_x))  > err:
        previous_x = x.copy()
        if verbose: print(f"x = {x}")
        for i in range(len(x)):
            x[i] = (N[i] @ x + b[i]) / M[i]
            # on utilise à droite le x modifié (au lieu de previous_x)
    return x

In [7]:
A = np.random.randint(10, size=(4,4))
A = A + np.diag(A.sum(axis=0))
b = A.sum(axis=1)                     # ainsi la solution est [1,1,1,1]
print('A:\n', A, "\nb:\n", b, "\n")

solve_jacobi2(A,b, verbose=True)

A:
 [[10  9  0  2]
 [ 0 20  2  2]
 [ 2  0 22  9]
 [ 8  3  2 23]] 
b:
 [21 24 33 36] 

x = [0.4515215346 0.8238676687 0.356323076  0.0146199734]
x = [1.3555951035 1.1629056951 1.3707831833 0.8228241617]
x = [0.8888200421 0.9806392655 1.0825882936 1.0340150121]
x = [1.0106216586 0.9883396694 0.9851191624 0.9991204086]
x = [1.0106702158 1.0015760429 0.9993898132 0.9961361095]
x = [0.9993543395 1.0004474077 1.0016393789 1.0000236654]
x = [0.9995926    0.9998336956 1.0000273551 1.0001610175]
x = [1.0001174705 0.9999811627 0.9999234501 0.9999682543]
x = [1.0000233027 1.0000108296 1.0000108685 0.9999895371]
x = [0.999992346  0.9999999594 1.0000049761 1.0000022349]
x = [0.9999995895 0.9999992789 0.9999991231 1.0000003131]
x = [1.0000005864 1.0000000564 0.9999998186 0.9999998045]
x = [0.9999999884 1.0000000377 1.0000000811 0.9999999921]


array([0.9999999677, 0.9999999927, 1.0000000062, 1.0000000117])

La méthode de base de Jacobi sur le même système matriciel prend nettement plus d'itérations :

In [8]:
M = np.diag(A)        # attention, c'est un vecteur
N = np.diag(M) - A    # np.diag d'une matrice donne un vecteur, np.diag d'un vecteur donne une matrice
print(f"M:\n {np.diag(M)}\nN:\n {N}\n")

x = np.random.random(4)
previous_x = np.zeros(len(b))
err = (1E-6 / 10) ** 2
while np.sum(np.square(x - previous_x))  > err:
    previous_x = x.copy()
    print(f"x = {x}")
    x = (N @ x + b) / M

M:
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 22  0]
 [ 0  0  0 23]]
N:
 [[ 0 -9  0 -2]
 [ 0  0 -2 -2]
 [-2  0  0 -9]
 [-8 -3 -2  0]]

x = [0.9968352522 0.128600433  0.4522385872 0.7247519759]
x = [1.8393092152 1.0823009437 1.1128891688 1.1623930221]
x = [0.8934505462 0.9724717809 0.8572656532 0.6875150048]
x = [1.0872723962 1.0455219342 1.1375210847 1.0530629992]
x = [0.9484176594 0.9809415916 0.9703585552 0.9517483851]
x = [1.0268028905 1.007789306  1.0244286007 1.02300508  ]
x = [0.9883886086 0.9952566319 0.9881522045 0.9875370329]
x = [1.0067616247 1.0024310763 1.0061540676 1.0056876881]
x = [0.9966744937 0.9988158244 0.9970585254 0.9967958973]
x = [1.0017065785 1.0006145577 1.001613088  1.0015669359]
x = [0.9991335109 0.9996819976 0.9992038373 0.9991859792]
x = [1.0004490063 1.0001610184 1.0004117802 1.0004120976]
x = [0.999772664  0.9999176122 0.9997905958 0.9997870145]
x = [1.0001167461 1.000042239  1.0001077973 1.0001080287]
x = [0.9999403792 0.9999784174 0.9999451932 0.9999445095]

## Bonus

Avoir une boucle qui travaille sur les indices n'est pas satisfaisant. Essayons de comprendre ce qui se passe lorsqu'on utilise la valeur modifiée de `x` dans la boucle `for`. À un instant donnée, lorsque `i == 3` par exemple, les valeurs précédentes, `x[0], x[1], x[2]`, ont déjà été mises à jour. Par contre les valeurs qui suivent, `x[4], x[5]...` sont toujours les anciennes. Donc les valeurs à gauche de la diagonale sont les nouvelles quand celles à droite de la diagonale sont les anciennces.

Cela revient à découper la matrice **A** en une matrice triangulaire inférieure **L** - une matrice triangulaire supérieure strictement **U**. Maintenant la méthode itérative est

$$
{\bf L} \, {\bf x}^{k+1} = {\bf U} \, {\bf x}^k + {\bf b}
$$

Inverser **L** est compliqué mais résoudre ${\bf L} \, {\bf x} = {\bf y}$ est rapide comme on l'a déjà vu. Alors faisons cela :

In [8]:
def solve_jacobi2_bonus(A, b, error=1E-6, verbose=False):
    L = np.tril(A) 
    U = -np.triu(A, k=1) 
    if verbose: print(f"L:\n {L}\nU\n {U}\n")
    previous_x = np.zeros(len(b))
    x = np.random.random(len(b))
    err = (error / 10) ** 2
    while np.sum(np.square(x - previous_x))  > err:
        previous_x = x.copy()
        if verbose: print(f"x = {x}")
        # on résoud  L x = U x + b  avec L matrice triangulaire inférieure
        y = U @ x + b
        x[0] = y[0] / L[0,0]
        for i in range(1,len(L)):
            x[i] = (y[i] - L[i,:i] @ x[:i]) / L[i,i]
    return x

In [9]:
print('A:\n', A, "\nb:\n", b, "\n")

solve_jacobi2_bonus(A,b, verbose=True)

A:
 [[17  4  0  1]
 [ 4  6  7  5]
 [ 3  1 26  0]
 [ 6  1  5 24]] 
b:
 [22 22 30 36] 

L:
 [[17  0  0  0]
 [ 4  6  0  0]
 [ 3  1 26  0]
 [ 6  1  5 24]]
U
 [[ 0 -4  0 -1]
 [ 0  0 -7 -5]
 [ 0  0  0  0]
 [ 0  0  0  0]]

x = [0.6770101989 0.1348901261 0.0277373762 0.5330641775]
x = [1.2310220775 2.3694048615 0.9206741887 0.9017121554]
x = [0.6835687293 1.3854074975 1.0216879352 1.0585308521]
x = [0.9058728916 0.9886731044 1.01129647   1.0216502998]
x = [1.0013916048 0.9678511319 1.0010759251 1.0007674839]
x = [1.0075192934 0.9930923218 0.9993980691 0.9985333988]
x = [1.0017116067 1.0007833492 0.9997723781 0.99958688  ]
x = [0.9998399837 1.0007165031 0.9999909056 1.0000120444]
x = [0.9998307025 1.0001134381 1.0000151713 1.0000344371]
x = [0.999971283  0.9999727472 1.0000043617 1.0000074061]
x = [1.0000059768 0.9999847551 0.9999998967 0.9999991625]
x = [1.0000036363 0.9999983942 0.9999996422 0.9999992324]
x = [1.000000423  1.0000007751 0.9999999214 0.9999998783]
x = [0.9999998248 1.0000003099

array([0.9999999953, 0.9999999802, 1.0000000013, 1.0000000017])